### ISSUE TITLE
Mod+D does not hold the Alt modifier on Alt+Tab as default firmware does

### ISSUE THREAD

**Issue by Glutnix** [kareltucek/firmware#57] opened 2021-03-26 01:16 UTC
Out of the box, the UHK has Mod+D configured to send Alt+Tab. 

On the default firmware (I'm using 8.10.7) holding Mod and tapping the D invokes the Windows app switcher. While holding Mod, the app switcher stays open, so further tapping of D would further switch apps. 

I assume this is because the default firmware 'Holds the Alt' modifier until you either release the Mod key or until another set of modifiers (or none) is required. Regular "alt+tab" works as intended: it is releasing the alt modifier that closes the app switcher.

It also lets Mod+S and Mod+F be used as Ctrl+Alt+Left and Right once the app switcher is open.

However, it seems that using the KT firmware breaks that behaviour. Am I missing something?

I file this against uhk-firmware-8.10.3.kt.1.tar.gz.

**Comment by kareltucek** [comment] 2021-03-26 01:28
Interesting... I have tested it right now against my local binary, and sticky mods on Alt+Tab work just fine. Will give it some time over weekend...

Can you export your userconfig so that I can take a look?

**Comment by kareltucek** [comment] 2021-08-12 15:32
I am still not aware of any difference in sticky mod behaviour between the fork and stock, therefore (and for lack of replies), I am closing this. Still, feel free to follow up.

**Closed as completed by kareltucek** 2021-08-12 15:32 UTC

**Comment by kareltucek** [comment] 2021-08-21 09:49
Fixed (in next release). Caused by a typo which broke the ActiveLayerHeld flag. Only one of the two switcher types was affected.
